package com.iesfilipinas.dam;

public enum TiposDeTerreno {

    AGUA, CASA, ESCALERA, SOTANO, CASETAPERRO, JARDIN, COBERTIZO, CONTINENTE,
    ENTRADA, SALON, HABITACION, COCINA, COMEDOR, SALACUADRO, PASILLO, HABITACIONNINO,
    HABITACIONPADRE, DESCONOCIDO;

}
