package com.iesfilipinas.dam.vespertino.mapa;

public enum TiposDeTerreno {

    AGUA, CASA, ESCALERA, SOTANO, CASETA, JARDIN, COBERTIZO, CONTINENTE,
    ENTRADA, SALON, HABITACION, COCINA, COMEDOR, MUSEO, PASILLO, DORMITORIO_INFANTIL,
    DORMITORIO, INICIO, DESCONOCIDO;

}
